include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_empty_else: true
    avoid_types_as_parameter_names: true
    avoid_redundant_argument_values: true
    prefer_single_quotes: true
    prefer_expression_function_bodies: true
    prefer_final_fields: true
    prefer_asserts_with_message: true
    parameter_assignments: true
