name: pokedex
description: Flutter tech test for Orbi.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # graphics
  flutter_svg: ^1.1.5

  # storage
  hive: ^2.1.0
  hive_flutter: ^1.1.0

  # network
  http: ^0.13.5
  http_interceptor: ^1.0.2
  pokeapi: ^1.0.3
  cached_network_image: ^3.2.2

  # utils
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.5
  infinite_scroll_pagination: ^4.0.0
  flutter_animation_progress_bar: ^2.3.1
  path_provider: ^2.0.9
  flutter_native_splash: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
